--- 
abstract: Geocoding plugin
author: Yung-chung Lin (henearkrxern@gmail.com)
distribution_type: module
generated_by: Module::Install version 0.67
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Catalyst-Plugin-Geocoding
no_index: 
  directory: 
    - inc
    - t
requires: 
  LWP: 0
version: 0.01
